# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage:
  displayName: Security Scanning
  jobs:
  - job:
    displayName: TFSec Scanning
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: './'
- stage:
  displayName: Terraform Deployment
  jobs:
  - job: TerraformDeployment
    displayName: Terraform Deployment
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: 'Install terraform'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: '(Cloudfront_Terraform)AWS_for_terrafrom'
        backendAWSBucketName: 'ohbster-ado-terraform-class5'
        backendAWSKey: 'cloudfront/terraform.tfstate'
      displayName: 'Initialize terraform'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'apply'
        commandOptions: '--auto-approve'
        environmentServiceNameAWS: '(Cloudfront_Terraform)AWS_for_terrafrom'
      displayName: 'Apply terraform'
    - bash: |
        terraform show --json | jq '.values.outputs.distribution_id.value'
        echo "##vso[task.setvariable variable=foo;isOutput=true]$foo"
# - stage:
#   displayName: SAST
#   jobs:
#   - job: SecurityScan    
#     steps:
#     - task: tfsec@1
#       inputs:
#         version: 'v1.26.0'
#         debug: true
